siteTitle = "Pitt Pauly"
siteDescr = "Software development contractor & rock climber"
siteAuthor = "Pitt Pauly"

siteLinkedInUrl = "http://linkedin.com/in/pierrepauly/"
siteTwitterUrl = "https://twitter.com/Pitt_pauly"
siteEmail = "contact@pittpauly.com"
siteBlog = "https://medium.com/@Pitt_Pauly"

siteGithubUrl = "https://github.com/Pitt-Pauly"
siteStackOverflow = "http://stackoverflow.com/story/pierrepauly"

siteUKC= "https://www.ukclimbing.com/logbook/showlog.html?id=175766"

googleAnalyticsId = ""

linkPrefix = ""
