siteTitle = "Pitt Pauly"
siteDescr = "Software development contractor & rock climber"
siteAuthor = "Pitt Pauly"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/Pitt_pauly"
siteGithubUrl = "https://github.com/Pitt-Pauly"
siteEmailUrl = "mailto:contact@pittpauly.com"
siteSkypeName = "live:contact_54041"
siteStackOverflow = "http://stackoverflow.com/users/1001286/pitt"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/gatsby-direct"
